### ISSUE TITLE
Custom Kibana mapping change should be more resilient.

### ISSUE THREAD

**Issue by bphenriques** [ppadovani/KibanaNestedSupportPlugin#93]
**Plugin version**: 1.0.0

**Kibana version**: 6.3.2

**Plugins installed**: None

**Description of the problem including expected versus actual behavior**:
Two unexpected behaviors:
```
Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
```
and the fact that the toggle box does not stay checked:
![44848137-94943400-ac4d-11e8-876b-3ab3990fa0c9](https://user-images.githubusercontent.com/4727729/44899765-9831c480-acfa-11e8-8855-2744db7d1d97.gif)

Expected that when I toggled the check-box, the button would stay checked and that I wouldn't have this error.

**Steps to reproduce**:

Elasticsearch 6.3.0 with several events on a index `test` with the following document structure:
```
{
    ...
    "fields": { 
          "value": 10,
          /* other regular fields */r
    }
    "system": {
         /* regular fields */
         "nestedTypeA": [ { A_1 }, { A_2 }, ..., { A_N } ]  // nested type
         "nestedTypeB": [ { B_1 }, { B_2 }, ..., { B_N } ]  // nested type
    }
}
```

The major characteristic is that both `nestedTypeA` and `nestedTypeB` fields are nested and they are inside the `system` field. In my use-case I want to display tables that present the sum of `value` given the aggregation term `system.nestedTypeA.id.keyword`. Ideally I would want to display `system.nestedType.name.keyword` next to the id. In short, I just want to make sure that both these nested fields are retrieved correctly so that I can design tabular views. The trickiest part is that in order to get the `value` I need to use `reverse_nested: { }`: 

1. Delete `.kibana` index
2. Deploy Kibana (Kubernetes)
3. Created index-pattern
4. `curl -X GET "localhost:9200/.kibana/_search"`, checked the index-pattern document and does not contain any mention to `nested` ([follow up from other issue](https://github.com/ppadovani/KibanaNestedSupportPlugin/issues/58#issuecomment-417359399)
5. Install plugin:
```
./bin/kibana-plugins install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.3.2-1.0.0/nested-fields-support-6.3.2-1.0.0.zip
```
6. Restart Kibana (delete Pod)
7. Install plugin again
8. In `Management`, enabled nested fields for the index-pattern I have set up previously.
9. Change tab and go back: the check-box was unchecked. Repeated these several times. Noticed that the top colored loading bar in Kibana appears so I assume that something was happening behind the scenes
10. Went to Index-patterns tab and refreshed the index only to encounter the following message:
```
Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
```

Also did a variation where I skipped 6 (and 7). The result was identical.

**Errors in browser console (if relevant)**:
The error in Kibana
```
Error: mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed: [strict_dynamic_mapping_exception] mapping set to strict, dynamic introduction of [nested] within [index-pattern] is not allowed
```

**Provide logs and/or server output (if relevant)**: N/A

**If using docker, include your docker file**: Kubernetes environment. File mostly identical to [this](https://github.com/helm/charts/blob/master/stable/kibana/values.yaml).
```
image:
  repository: "docker.elastic.co/kibana/kibana"
  tag: "6.3.0"
  pullPolicy: "IfNotPresent"

commandline:
  args:

env:
  # All Kibana configuration options are adjustable via env vars.
  # To adjust a config option to an env var uppercase + replace `.` with `_`
  # Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
  #
  ELASTICSEARCH_URL: http://elasticsearch:9200
  # SERVER_PORT: 5601
  # LOGGING_VERBOSE: "true"
  # SERVER_DEFAULTROUTE: "/app/kibana"

service:
  type: ClusterIP
  externalPort: 443
  internalPort: 5601
  ## External IP addresses of service
  ## Default: nil
  ##
  # externalIPs:
  # - 192.168.0.1
  #
  ## LoadBalancer IP if service.type is LoadBalancer
  ## Default: nil
  ##
  # loadBalancerIP: 10.2.2.2
  annotations:
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT

ingress:
  enabled: true
  hosts:
    - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 300Mi
  # requests:
  #   cpu: 100m
  #   memory: 300Mi

# Affinity for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
# affinity: {}

# Tolerations for pod assignment
# Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

podAnnotations: {}
replicaCount: 1
```
Also a sample of the mapping of the document:
`GET /test/_mapping/_doc`
```
...
          "fields": {
            "properties": {
              "value": {
                "type": "long"
              },
...

              "nestedTypeA": {
                "type": "nested",
...

             "nestedTypeB": {
                "type": "nested",

...
```
